import { useEffect, useRef } from 'react'
import ReactMarkdown from 'react-markdown'
import styles from './ResultCard.module.css'

export default function ResultCard({ result, onReset }) {
  const cardRef = useRef(null)

  useEffect(() => {
    if (cardRef.current) {
      cardRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' })
    }
  }, [result])

  return (
    <div className={styles.card} ref={cardRef}>
      {/* ── Header ── */}
      <div className={styles.cardHeader}>
        <div className={styles.verdictBadge}>
          <span className={styles.verdictIcon}>⚖</span>
          <span>Legal Analysis Complete</span>
        </div>
        <button className={styles.resetBtn} onClick={onReset}>
          ← New Case
        </button>
      </div>

      <div className={styles.greeting}>
        Dear <strong>{result.name}</strong>, here is the legal analysis for your case:
      </div>

      {/* ── Top Stats Grid ── */}
      <div className={styles.statsGrid}>
        <StatBlock
          icon="🏷"
          label="Case Category"
          value={result.category}
          accent="gold"
        />
        <StatBlock
          icon="👨‍⚖️"
          label="Recommended Lawyer"
          value={result.recommended_lawyer}
          accent="teal"
        />
      </div>

      {/* ── IPC Sections ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>
          <span className={styles.sectionIcon}>📋</span>
          Applicable IPC Sections
        </h3>
        <div className={styles.ipcGrid}>
          {result.ipc_sections.map((sec, i) => (
            <div key={i} className={styles.ipcChip}>
              {sec}
            </div>
          ))}
        </div>
      </section>

      {/* ── Summary ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>
          <span className={styles.sectionIcon}>📝</span>
          Case Summary
        </h3>
        <div className={styles.summaryBox}>
          <p className={styles.summaryText}>{result.summary}</p>
        </div>
      </section>

      {/* ── Full Analysis ── */}
      <section className={styles.section}>
        <h3 className={styles.sectionTitle}>
          <span className={styles.sectionIcon}>🧠</span>
          Full Legal Analysis
        </h3>
        <div className={styles.analysisBox}>
          <ReactMarkdown
            components={{
              p: ({ children }) => <p className={styles.mdPara}>{children}</p>,
              h1: ({ children }) => <h4 className={styles.mdH}>{children}</h4>,
              h2: ({ children }) => <h4 className={styles.mdH}>{children}</h4>,
              h3: ({ children }) => <h4 className={styles.mdH}>{children}</h4>,
              ul: ({ children }) => <ul className={styles.mdUl}>{children}</ul>,
              ol: ({ children }) => <ol className={styles.mdOl}>{children}</ol>,
              li: ({ children }) => <li className={styles.mdLi}>{children}</li>,
              strong: ({ children }) => <strong className={styles.mdStrong}>{children}</strong>,
              code: ({ children }) => <code className={styles.mdCode}>{children}</code>,
            }}
          >
            {result.full_analysis}
          </ReactMarkdown>
        </div>
      </section>

      {/* ── Disclaimer ── */}
      <div className={styles.disclaimer}>
        <span className={styles.disclaimerIcon}>ℹ</span>
        <p>
          This analysis is generated by AI for informational purposes only and does not constitute legal advice.
          Always consult a qualified advocate for professional legal counsel.
        </p>
      </div>
    </div>
  )
}

function StatBlock({ icon, label, value, accent }) {
  return (
    <div className={`${styles.statBlock} ${styles[`accent_${accent}`]}`}>
      <span className={styles.statIcon}>{icon}</span>
      <div>
        <div className={styles.statLabel}>{label}</div>
        <div className={styles.statValue}>{value}</div>
      </div>
    </div>
  )
}
